[package]
name = "ephemeral_id_rust"
version = "0.1.0"
authors = ["Maciej Kasprzyk <maciej.kasprzyk@shareablee.com>"]
edition = "2018"

[dependencies]
rust-crypto = "0.2.36"
ring = "0.14.4"
hmac = "0.7.0"
hex = "0.3.1"

[dependencies.x25519-dalek]
version = "^0.4"
